In [1]:
import pandas as pd
poke = pd.read_csv(r'C:\Users\DELL\Downloads\datasets\POKEMON.csv')
poke

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [33]:
poke.head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False

In [11]:
poke.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary', 'summed_rows'],
      dtype='object')

In [49]:
poke[['Name', 'Type 1']][0:5]

                    Name Type 1
0              Bulbasaur  Grass
1                Ivysaur  Grass
2               Venusaur  Grass
3  VenusaurMega Venusaur  Grass
4             Charmander   Fire

In [13]:
poke.iloc[0:801, 4:10] # poke.iloc[rows, columns]

     HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
0    45      49       49       65       65     45
1    60      62       63       80       80     60
2    80      82       83      100      100     80
3    80     100      123      122      120     80
4    39      52       43       60       50     65
..   ..     ...      ...      ...      ...    ...
795  50     100      150      100      150     50
796  50     160      110      160      110    110
797  80     110       60      150      130     70
798  80     160       60      170      130     80
799  80     110      120      130       90     70

[800 rows x 6 columns]

In [59]:
 poke.iloc[4] # iloc locates rows in a data using indexing

#                      4
Name          Charmander
Type 1              Fire
Type 2               NaN
Total                309
HP                    39
Attack                52
Defense               43
Sp. Atk               60
Sp. Def               50
Speed                 65
Generation             1
Legendary          False
Name: 4, dtype: object

In [75]:
# read a specific location
poke.iloc[796, 3]

'Fairy'

In [99]:
poke.loc[poke['Name']=='Blastoise'] #locates data using names of data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False

In [107]:
poke.loc[:, 'Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [11]:
for index, row in poke.iterrows():
    print(f"Row {index}: '{row['Name']}'")

Row 0: 'Bulbasaur'
Row 1: 'Ivysaur'
Row 2: 'Venusaur'
Row 3: 'VenusaurMega Venusaur'
Row 4: 'Charmander'
Row 5: 'Charmeleon'
Row 6: 'Charizard'
Row 7: 'CharizardMega Charizard X'
Row 8: 'CharizardMega Charizard Y'
Row 9: 'Squirtle'
Row 10: 'Wartortle'
Row 11: 'Blastoise'
Row 12: 'BlastoiseMega Blastoise'
Row 13: 'Caterpie'
Row 14: 'Metapod'
Row 15: 'Butterfree'
Row 16: 'Weedle'
Row 17: 'Kakuna'
Row 18: 'Beedrill'
Row 19: 'BeedrillMega Beedrill'
Row 20: 'Pidgey'
Row 21: 'Pidgeotto'
Row 22: 'Pidgeot'
Row 23: 'PidgeotMega Pidgeot'
Row 24: 'Rattata'
Row 25: 'Raticate'
Row 26: 'Spearow'
Row 27: 'Fearow'
Row 28: 'Ekans'
Row 29: 'Arbok'
Row 30: 'Pikachu'
Row 31: 'Raichu'
Row 32: 'Sandshrew'
Row 33: 'Sandslash'
Row 34: 'Nidoranâ™€'
Row 35: 'Nidorina'
Row 36: 'Nidoqueen'
Row 37: 'Nidoranâ™‚'
Row 38: 'Nidorino'
Row 39: 'Nidoking'
Row 40: 'Clefairy'
Row 41: 'Clefable'
Row 42: 'Vulpix'
Row 43: 'Ninetales'
Row 44: 'Jigglypuff'
Row 45: 'Wigglytuff'
Row 46: 'Zubat'
Row 47: 'Golbat'
Row 48: 'Oddish'
Row 49: 'Gloom'
Row 50: 'Vileplume'
Row 51: 'Paras'
Row 52: 'Parasect'
Row 53: 'Venonat'
Row 54: 'Venomoth'
Row 55: 'Diglett'
Row 56: 'Dugtrio'
Row 57: 'Meowth'
Row 58: 'Persian'
Row 59: 'Psyduck'
Row 60: 'Golduck'
Row 61: 'Mankey'
Row 62: 'Primeape'
Row 63: 'Growlithe'
Row 64: 'Arcanine'
Row 65: 'Poliwag'
Row 66: 'Poliwhirl'
Row 67: 'Poliwrath'
Row 68: 'Abra'
Row 69: 'Kadabra'
Row 70: 'Alakazam'
Row 71: 'AlakazamMega Alakazam'
Row 72: 'Machop'
Row 73: 'Machoke'
Row 74: 'Machamp'
Row 75: 'Bellsprout'
Row 76: 'Weepinbell'
Row 77: 'Victreebel'
Row 78: 'Tentacool'
Row 79: 'Tentacruel'
Row 80: 'Geodude'
Row 81: 'Graveler'
Row 82: 'Golem'
Row 83: 'Ponyta'
Row 84: 'Rapidash'
Row 85: 'Slowpoke'
Row 86: 'Slowbro'
Row 87: 'SlowbroMega Slowbro'
Row 88: 'Magnemite'
Row 89: 'Magneton'
Row 90: 'Farfetch'd'
Row 91: 'Doduo'
Row 92: 'Dodrio'
Row 93: 'Seel'
Row 94: 'Dewgong'
Row 95: 'Grimer'
Row 96: 'Muk'
Row 97: 'Shellder'
Row 98: 'Cloyster'
Row 99: 'Gastly'
Row 100: 'Haunter'
Row 101: 'Gengar'
Row 102: 'GengarMega Gengar'
Row 103: 'Onix'
Row 104: 'Drowzee'
Row 105: 'Hypno'
Row 106: 'Krabby'
Row 107: 'Kingler'
Row 108: 'Voltorb'
Row 109: 'Electrode'
Row 110: 'Exeggcute'
Row 111: 'Exeggutor'
Row 112: 'Cubone'
Row 113: 'Marowak'
Row 114: 'Hitmonlee'
Row 115: 'Hitmonchan'
Row 116: 'Lickitung'
Row 117: 'Koffing'
Row 118: 'Weezing'
Row 119: 'Rhyhorn'
Row 120: 'Rhydon'
Row 121: 'Chansey'
Row 122: 'Tangela'
Row 123: 'Kangaskhan'
Row 124: 'KangaskhanMega Kangaskhan'
Row 125: 'Horsea'
Row 126: 'Seadra'
Row 127: 'Goldeen'
Row 128: 'Seaking'
Row 129: 'Staryu'
Row 130: 'Starmie'
Row 131: 'Mr. Mime'
Row 132: 'Scyther'
Row 133: 'Jynx'
Row 134: 'Electabuzz'
Row 135: 'Magmar'
Row 136: 'Pinsir'
Row 137: 'PinsirMega Pinsir'
Row 138: 'Tauros'
Row 139: 'Magikarp'
Row 140: 'Gyarados'
Row 141: 'GyaradosMega Gyarados'
Row 142: 'Lapras'
Row 143: 'Ditto'
Row 144: 'Eevee'
Row 145: 'Vaporeon'
Row 146: 'Jolteon'
Row 147: 'Flareon'
Row 148: 'Porygon'
Row 149: 'Omanyte'
Row 150: 'Omastar'
Row 151: 'Kabuto'
Row 152: 'Kabutops'
Row 153: 'Aerodactyl'
Row 154: 'AerodactylMega Aerodactyl'
Row 155: 'Snorlax'
Row 156: 'Articuno'
Row 157: 'Zapdos'
Row 158: 'Moltres'
Row 159: 'Dratini'
Row 160: 'Dragonair'
Row 161: 'Dragonite'
Row 162: 'Mewtwo'
Row 163: 'MewtwoMega Mewtwo X'
Row 164: 'MewtwoMega Mewtwo Y'
Row 165: 'Mew'
Row 166: 'Chikorita'
Row 167: 'Bayleef'
Row 168: 'Meganium'
Row 169: 'Cyndaquil'
Row 170: 'Quilava'
Row 171: 'Typhlosion'
Row 172: 'Totodile'
Row 173: 'Croconaw'
Row 174: 'Feraligatr'
Row 175: 'Sentret'
Row 176: 'Furret'
Row 177: 'Hoothoot'
Row 178: 'Noctowl'
Row 179: 'Ledyba'
Row 180: 'Ledian'
Row 181: 'Spinarak'
Row 182: 'Ariados'
Row 183: 'Crobat'
Row 184: 'Chinchou'
Row 185: 'Lanturn'
Row 186: 'Pichu'
Row 187: 'Cleffa'
Row 188: 'Igglybuff'
Row 189: 'Togepi'
Row 190: 'Togetic'
Row 191: 'Natu'
Row 192: 'Xatu'
Row 193: 'Mareep'
Row 194: 'Flaaffy'
Row 195: 'Ampharos'
Row 196: 'AmpharosMega Ampharos'
Row 197: 'Bellossom'
Row 198: 'Marill'
Row 199: 'Azumarill'
Row 200: 'Sudowoodo'
Row 201: 'Politoed'
Row 202: 'Hoppip'
Row 203: 'Skiploom'
Row 204: 'Jumpluff'
Row 205: 'Aipom'
Row 206: 'Sunkern'
Row 207: 'Sunflora'
Row 208: 'Yanma'
Row 209: 'Wooper'
Row 210: 'Quagsire'
Row 211: 'Espeon'
Row 212: 'Umbreon'
Row 213: 'Murkrow'
Row 214: 'Slowking'
Row 215: 'Misdreavus'
Row 216: 'Unown'
Row 217: 'Wobbuffet'
Row 218: 'Girafarig'
Row 219: 'Pineco'
Row 220: 'Forretress'
Row 221: 'Dunsparce'
Row 222: 'Gligar'
Row 223: 'Steelix'
Row 224: 'SteelixMega Steelix'
Row 225: 'Snubbull'
Row 226: 'Granbull'
Row 227: 'Qwilfish'
Row 228: 'Scizor'
Row 229: 'ScizorMega Scizor'
Row 230: 'Shuckle'
Row 231: 'Heracross'
Row 232: 'HeracrossMega Heracross'
Row 233: 'Sneasel'
Row 234: 'Teddiursa'
Row 235: 'Ursaring'
Row 236: 'Slugma'
Row 237: 'Magcargo'
Row 238: 'Swinub'
Row 239: 'Piloswine'
Row 240: 'Corsola'
Row 241: 'Remoraid'
Row 242: 'Octillery'
Row 243: 'Delibird'
Row 244: 'Mantine'
Row 245: 'Skarmory'
Row 246: 'Houndour'
Row 247: 'Houndoom'
Row 248: 'HoundoomMega Houndoom'
Row 249: 'Kingdra'
Row 250: 'Phanpy'
Row 251: 'Donphan'
Row 252: 'Porygon2'
Row 253: 'Stantler'
Row 254: 'Smeargle'
Row 255: 'Tyrogue'
Row 256: 'Hitmontop'
Row 257: 'Smoochum'
Row 258: 'Elekid'
Row 259: 'Magby'
Row 260: 'Miltank'
Row 261: 'Blissey'
Row 262: 'Raikou'
Row 263: 'Entei'
Row 264: 'Suicune'
Row 265: 'Larvitar'
Row 266: 'Pupitar'
Row 267: 'Tyranitar'
Row 268: 'TyranitarMega Tyranitar'
Row 269: 'Lugia'
Row 270: 'Ho-oh'
Row 271: 'Celebi'
Row 272: 'Treecko'
Row 273: 'Grovyle'
Row 274: 'Sceptile'
Row 275: 'SceptileMega Sceptile'
Row 276: 'Torchic'
Row 277: 'Combusken'
Row 278: 'Blaziken'
Row 279: 'BlazikenMega Blaziken'
Row 280: 'Mudkip'
Row 281: 'Marshtomp'
Row 282: 'Swampert'
Row 283: 'SwampertMega Swampert'
Row 284: 'Poochyena'
Row 285: 'Mightyena'
Row 286: 'Zigzagoon'
Row 287: 'Linoone'
Row 288: 'Wurmple'
Row 289: 'Silcoon'
Row 290: 'Beautifly'
Row 291: 'Cascoon'
Row 292: 'Dustox'
Row 293: 'Lotad'
Row 294: 'Lombre'
Row 295: 'Ludicolo'
Row 296: 'Seedot'
Row 297: 'Nuzleaf'
Row 298: 'Shiftry'
Row 299: 'Taillow'
Row 300: 'Swellow'
Row 301: 'Wingull'
Row 302: 'Pelipper'
Row 303: 'Ralts'
Row 304: 'Kirlia'
Row 305: 'Gardevoir'
Row 306: 'GardevoirMega Gardevoir'
Row 307: 'Surskit'
Row 308: 'Masquerain'
Row 309: 'Shroomish'
Row 310: 'Breloom'
Row 311: 'Slakoth'
Row 312: 'Vigoroth'
Row 313: 'Slaking'
Row 314: 'Nincada'
Row 315: 'Ninjask'
Row 316: 'Shedinja'
Row 317: 'Whismur'
Row 318: 'Loudred'
Row 319: 'Exploud'
Row 320: 'Makuhita'
Row 321: 'Hariyama'
Row 322: 'Azurill'
Row 323: 'Nosepass'
Row 324: 'Skitty'
Row 325: 'Delcatty'
Row 326: 'Sableye'
Row 327: 'SableyeMega Sableye'
Row 328: 'Mawile'
Row 329: 'MawileMega Mawile'
Row 330: 'Aron'
Row 331: 'Lairon'
Row 332: 'Aggron'
Row 333: 'AggronMega Aggron'
Row 334: 'Meditite'
Row 335: 'Medicham'
Row 336: 'MedichamMega Medicham'
Row 337: 'Electrike'
Row 338: 'Manectric'
Row 339: 'ManectricMega Manectric'
Row 340: 'Plusle'
Row 341: 'Minun'
Row 342: 'Volbeat'
Row 343: 'Illumise'
Row 344: 'Roselia'
Row 345: 'Gulpin'
Row 346: 'Swalot'
Row 347: 'Carvanha'
Row 348: 'Sharpedo'
Row 349: 'SharpedoMega Sharpedo'
Row 350: 'Wailmer'
Row 351: 'Wailord'
Row 352: 'Numel'
Row 353: 'Camerupt'
Row 354: 'CameruptMega Camerupt'
Row 355: 'Torkoal'
Row 356: 'Spoink'
Row 357: 'Grumpig'
Row 358: 'Spinda'
Row 359: 'Trapinch'
Row 360: 'Vibrava'
Row 361: 'Flygon'
Row 362: 'Cacnea'
Row 363: 'Cacturne'
Row 364: 'Swablu'
Row 365: 'Altaria'
Row 366: 'AltariaMega Altaria'
Row 367: 'Zangoose'
Row 368: 'Seviper'
Row 369: 'Lunatone'
Row 370: 'Solrock'
Row 371: 'Barboach'
Row 372: 'Whiscash'
Row 373: 'Corphish'
Row 374: 'Crawdaunt'
Row 375: 'Baltoy'
Row 376: 'Claydol'
Row 377: 'Lileep'
Row 378: 'Cradily'
Row 379: 'Anorith'
Row 380: 'Armaldo'
Row 381: 'Feebas'
Row 382: 'Milotic'
Row 383: 'Castform'
Row 384: 'Kecleon'
Row 385: 'Shuppet'
Row 386: 'Banette'
Row 387: 'BanetteMega Banette'
Row 388: 'Duskull'
Row 389: 'Dusclops'
Row 390: 'Tropius'
Row 391: 'Chimecho'
Row 392: 'Absol'
Row 393: 'AbsolMega Absol'
Row 394: 'Wynaut'
Row 395: 'Snorunt'
Row 396: 'Glalie'
Row 397: 'GlalieMega Glalie'
Row 398: 'Spheal'
Row 399: 'Sealeo'
Row 400: 'Walrein'
Row 401: 'Clamperl'
Row 402: 'Huntail'
Row 403: 'Gorebyss'
Row 404: 'Relicanth'
Row 405: 'Luvdisc'
Row 406: 'Bagon'
Row 407: 'Shelgon'
Row 408: 'Salamence'
Row 409: 'SalamenceMega Salamence'
Row 410: 'Beldum'
Row 411: 'Metang'
Row 412: 'Metagross'
Row 413: 'MetagrossMega Metagross'
Row 414: 'Regirock'
Row 415: 'Regice'
Row 416: 'Registeel'
Row 417: 'Latias'
Row 418: 'LatiasMega Latias'
Row 419: 'Latios'
Row 420: 'LatiosMega Latios'
Row 421: 'Kyogre'
Row 422: 'KyogrePrimal Kyogre'
Row 423: 'Groudon'
Row 424: 'GroudonPrimal Groudon'
Row 425: 'Rayquaza'
Row 426: 'RayquazaMega Rayquaza'
Row 427: 'Jirachi'
Row 428: 'DeoxysNormal Forme'
Row 429: 'DeoxysAttack Forme'
Row 430: 'DeoxysDefense Forme'
Row 431: 'DeoxysSpeed Forme'
Row 432: 'Turtwig'
Row 433: 'Grotle'
Row 434: 'Torterra'
Row 435: 'Chimchar'
Row 436: 'Monferno'
Row 437: 'Infernape'
Row 438: 'Piplup'
Row 439: 'Prinplup'
Row 440: 'Empoleon'
Row 441: 'Starly'
Row 442: 'Staravia'
Row 443: 'Staraptor'
Row 444: 'Bidoof'
Row 445: 'Bibarel'
Row 446: 'Kricketot'
Row 447: 'Kricketune'
Row 448: 'Shinx'
Row 449: 'Luxio'
Row 450: 'Luxray'
Row 451: 'Budew'
Row 452: 'Roserade'
Row 453: 'Cranidos'
Row 454: 'Rampardos'
Row 455: 'Shieldon'
Row 456: 'Bastiodon'
Row 457: 'Burmy'
Row 458: 'WormadamPlant Cloak'
Row 459: 'WormadamSandy Cloak'
Row 460: 'WormadamTrash Cloak'
Row 461: 'Mothim'
Row 462: 'Combee'
Row 463: 'Vespiquen'
Row 464: 'Pachirisu'
Row 465: 'Buizel'
Row 466: 'Floatzel'
Row 467: 'Cherubi'
Row 468: 'Cherrim'
Row 469: 'Shellos'
Row 470: 'Gastrodon'
Row 471: 'Ambipom'
Row 472: 'Drifloon'
Row 473: 'Drifblim'
Row 474: 'Buneary'
Row 475: 'Lopunny'
Row 476: 'LopunnyMega Lopunny'
Row 477: 'Mismagius'
Row 478: 'Honchkrow'
Row 479: 'Glameow'
Row 480: 'Purugly'
Row 481: 'Chingling'
Row 482: 'Stunky'
Row 483: 'Skuntank'
Row 484: 'Bronzor'
Row 485: 'Bronzong'
Row 486: 'Bonsly'
Row 487: 'Mime Jr.'
Row 488: 'Happiny'
Row 489: 'Chatot'
Row 490: 'Spiritomb'
Row 491: 'Gible'
Row 492: 'Gabite'
Row 493: 'Garchomp'
Row 494: 'GarchompMega Garchomp'
Row 495: 'Munchlax'
Row 496: 'Riolu'
Row 497: 'Lucario'
Row 498: 'LucarioMega Lucario'
Row 499: 'Hippopotas'
Row 500: 'Hippowdon'
Row 501: 'Skorupi'
Row 502: 'Drapion'
Row 503: 'Croagunk'
Row 504: 'Toxicroak'
Row 505: 'Carnivine'
Row 506: 'Finneon'
Row 507: 'Lumineon'
Row 508: 'Mantyke'
Row 509: 'Snover'
Row 510: 'Abomasnow'
Row 511: 'AbomasnowMega Abomasnow'
Row 512: 'Weavile'
Row 513: 'Magnezone'
Row 514: 'Lickilicky'
Row 515: 'Rhyperior'
Row 516: 'Tangrowth'
Row 517: 'Electivire'
Row 518: 'Magmortar'
Row 519: 'Togekiss'
Row 520: 'Yanmega'
Row 521: 'Leafeon'
Row 522: 'Glaceon'
Row 523: 'Gliscor'
Row 524: 'Mamoswine'
Row 525: 'Porygon-Z'
Row 526: 'Gallade'
Row 527: 'GalladeMega Gallade'
Row 528: 'Probopass'
Row 529: 'Dusknoir'
Row 530: 'Froslass'
Row 531: 'Rotom'
Row 532: 'RotomHeat Rotom'
Row 533: 'RotomWash Rotom'
Row 534: 'RotomFrost Rotom'
Row 535: 'RotomFan Rotom'
Row 536: 'RotomMow Rotom'
Row 537: 'Uxie'
Row 538: 'Mesprit'
Row 539: 'Azelf'
Row 540: 'Dialga'
Row 541: 'Palkia'
Row 542: 'Heatran'
Row 543: 'Regigigas'
Row 544: 'GiratinaAltered Forme'
Row 545: 'GiratinaOrigin Forme'
Row 546: 'Cresselia'
Row 547: 'Phione'
Row 548: 'Manaphy'
Row 549: 'Darkrai'
Row 550: 'ShayminLand Forme'
Row 551: 'ShayminSky Forme'
Row 552: 'Arceus'
Row 553: 'Victini'
Row 554: 'Snivy'
Row 555: 'Servine'
Row 556: 'Serperior'
Row 557: 'Tepig'
Row 558: 'Pignite'
Row 559: 'Emboar'
Row 560: 'Oshawott'
Row 561: 'Dewott'
Row 562: 'Samurott'
Row 563: 'Patrat'
Row 564: 'Watchog'
Row 565: 'Lillipup'
Row 566: 'Herdier'
Row 567: 'Stoutland'
Row 568: 'Purrloin'
Row 569: 'Liepard'
Row 570: 'Pansage'
Row 571: 'Simisage'
Row 572: 'Pansear'
Row 573: 'Simisear'
Row 574: 'Panpour'
Row 575: 'Simipour'
Row 576: 'Munna'
Row 577: 'Musharna'
Row 578: 'Pidove'
Row 579: 'Tranquill'
Row 580: 'Unfezant'
Row 581: 'Blitzle'
Row 582: 'Zebstrika'
Row 583: 'Roggenrola'
Row 584: 'Boldore'
Row 585: 'Gigalith'
Row 586: 'Woobat'
Row 587: 'Swoobat'
Row 588: 'Drilbur'
Row 589: 'Excadrill'
Row 590: 'Audino'
Row 591: 'AudinoMega Audino'
Row 592: 'Timburr'
Row 593: 'Gurdurr'
Row 594: 'Conkeldurr'
Row 595: 'Tympole'
Row 596: 'Palpitoad'
Row 597: 'Seismitoad'
Row 598: 'Throh'
Row 599: 'Sawk'
Row 600: 'Sewaddle'
Row 601: 'Swadloon'
Row 602: 'Leavanny'
Row 603: 'Venipede'
Row 604: 'Whirlipede'
Row 605: 'Scolipede'
Row 606: 'Cottonee'
Row 607: 'Whimsicott'
Row 608: 'Petilil'
Row 609: 'Lilligant'
Row 610: 'Basculin'
Row 611: 'Sandile'
Row 612: 'Krokorok'
Row 613: 'Krookodile'
Row 614: 'Darumaka'
Row 615: 'DarmanitanStandard Mode'
Row 616: 'DarmanitanZen Mode'
Row 617: 'Maractus'
Row 618: 'Dwebble'
Row 619: 'Crustle'
Row 620: 'Scraggy'
Row 621: 'Scrafty'
Row 622: 'Sigilyph'
Row 623: 'Yamask'
Row 624: 'Cofagrigus'
Row 625: 'Tirtouga'
Row 626: 'Carracosta'
Row 627: 'Archen'
Row 628: 'Archeops'
Row 629: 'Trubbish'
Row 630: 'Garbodor'
Row 631: 'Zorua'
Row 632: 'Zoroark'
Row 633: 'Minccino'
Row 634: 'Cinccino'
Row 635: 'Gothita'
Row 636: 'Gothorita'
Row 637: 'Gothitelle'
Row 638: 'Solosis'
Row 639: 'Duosion'
Row 640: 'Reuniclus'
Row 641: 'Ducklett'
Row 642: 'Swanna'
Row 643: 'Vanillite'
Row 644: 'Vanillish'
Row 645: 'Vanilluxe'
Row 646: 'Deerling'
Row 647: 'Sawsbuck'
Row 648: 'Emolga'
Row 649: 'Karrablast'
Row 650: 'Escavalier'
Row 651: 'Foongus'
Row 652: 'Amoonguss'
Row 653: 'Frillish'
Row 654: 'Jellicent'
Row 655: 'Alomomola'
Row 656: 'Joltik'
Row 657: 'Galvantula'
Row 658: 'Ferroseed'
Row 659: 'Ferrothorn'
Row 660: 'Klink'
Row 661: 'Klang'
Row 662: 'Klinklang'
Row 663: 'Tynamo'
Row 664: 'Eelektrik'
Row 665: 'Eelektross'
Row 666: 'Elgyem'
Row 667: 'Beheeyem'
Row 668: 'Litwick'
Row 669: 'Lampent'
Row 670: 'Chandelure'
Row 671: 'Axew'
Row 672: 'Fraxure'
Row 673: 'Haxorus'
Row 674: 'Cubchoo'
Row 675: 'Beartic'
Row 676: 'Cryogonal'
Row 677: 'Shelmet'
Row 678: 'Accelgor'
Row 679: 'Stunfisk'
Row 680: 'Mienfoo'
Row 681: 'Mienshao'
Row 682: 'Druddigon'
Row 683: 'Golett'
Row 684: 'Golurk'
Row 685: 'Pawniard'
Row 686: 'Bisharp'
Row 687: 'Bouffalant'
Row 688: 'Rufflet'
Row 689: 'Braviary'
Row 690: 'Vullaby'
Row 691: 'Mandibuzz'
Row 692: 'Heatmor'
Row 693: 'Durant'
Row 694: 'Deino'
Row 695: 'Zweilous'
Row 696: 'Hydreigon'
Row 697: 'Larvesta'
Row 698: 'Volcarona'
Row 699: 'Cobalion'
Row 700: 'Terrakion'
Row 701: 'Virizion'
Row 702: 'TornadusIncarnate Forme'
Row 703: 'TornadusTherian Forme'
Row 704: 'ThundurusIncarnate Forme'
Row 705: 'ThundurusTherian Forme'
Row 706: 'Reshiram'
Row 707: 'Zekrom'
Row 708: 'LandorusIncarnate Forme'
Row 709: 'LandorusTherian Forme'
Row 710: 'Kyurem'
Row 711: 'KyuremBlack Kyurem'
Row 712: 'KyuremWhite Kyurem'
Row 713: 'KeldeoOrdinary Forme'
Row 714: 'KeldeoResolute Forme'
Row 715: 'MeloettaAria Forme'
Row 716: 'MeloettaPirouette Forme'
Row 717: 'Genesect'
Row 718: 'Chespin'
Row 719: 'Quilladin'
Row 720: 'Chesnaught'
Row 721: 'Fennekin'
Row 722: 'Braixen'
Row 723: 'Delphox'
Row 724: 'Froakie'
Row 725: 'Frogadier'
Row 726: 'Greninja'
Row 727: 'Bunnelby'
Row 728: 'Diggersby'
Row 729: 'Fletchling'
Row 730: 'Fletchinder'
Row 731: 'Talonflame'
Row 732: 'Scatterbug'
Row 733: 'Spewpa'
Row 734: 'Vivillon'
Row 735: 'Litleo'
Row 736: 'Pyroar'
Row 737: 'FlabÃ©bÃ©'
Row 738: 'Floette'
Row 739: 'Florges'
Row 740: 'Skiddo'
Row 741: 'Gogoat'
Row 742: 'Pancham'
Row 743: 'Pangoro'
Row 744: 'Furfrou'
Row 745: 'Espurr'
Row 746: 'MeowsticMale'
Row 747: 'MeowsticFemale'
Row 748: 'Honedge'
Row 749: 'Doublade'
Row 750: 'AegislashBlade Forme'
Row 751: 'AegislashShield Forme'
Row 752: 'Spritzee'
Row 753: 'Aromatisse'
Row 754: 'Swirlix'
Row 755: 'Slurpuff'
Row 756: 'Inkay'
Row 757: 'Malamar'
Row 758: 'Binacle'
Row 759: 'Barbaracle'
Row 760: 'Skrelp'
Row 761: 'Dragalge'
Row 762: 'Clauncher'
Row 763: 'Clawitzer'
Row 764: 'Helioptile'
Row 765: 'Heliolisk'
Row 766: 'Tyrunt'
Row 767: 'Tyrantrum'
Row 768: 'Amaura'
Row 769: 'Aurorus'
Row 770: 'Sylveon'
Row 771: 'Hawlucha'
Row 772: 'Dedenne'
Row 773: 'Carbink'
Row 774: 'Goomy'
Row 775: 'Sliggoo'
Row 776: 'Goodra'
Row 777: 'Klefki'
Row 778: 'Phantump'
Row 779: 'Trevenant'
Row 780: 'PumpkabooAverage Size'
Row 781: 'PumpkabooSmall Size'
Row 782: 'PumpkabooLarge Size'
Row 783: 'PumpkabooSuper Size'
Row 784: 'GourgeistAverage Size'
Row 785: 'GourgeistSmall Size'
Row 786: 'GourgeistLarge Size'
Row 787: 'GourgeistSuper Size'
Row 788: 'Bergmite'
Row 789: 'Avalugg'
Row 790: 'Noibat'
Row 791: 'Noivern'
Row 792: 'Xerneas'
Row 793: 'Yveltal'
Row 794: 'Zygarde50% Forme'
Row 795: 'Diancie'
Row 796: 'DiancieMega Diancie'
Row 797: 'HoopaHoopa Confined'
Row 798: 'HoopaHoopa Unbound'
Row 799: 'Volcanion'

In [3]:
poke.loc[poke['Type 1'] == 'Fire' ]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,534
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False,299
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False,505
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False,350
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False,555
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False,410
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False,500
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False,495
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False,525
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True,580
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False,309
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False,405
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False,534
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False,250
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False,410
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False,365
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True,580
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,680
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False,310
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False,405
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False,530
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False,630
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False,305
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False,460
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False,560
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False,470
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False,309
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False,405
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False,534
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False,540
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True,600
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False,308
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False,528
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False,316
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False,498
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False,315
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False,480
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False,540
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False,484
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False,307
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False,409
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False,534
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False,382
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False,499
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False,369
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False,507
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [25]:
poke.loc[poke['Type 1'] == 'Fire' ].filter(items = ['Name', 'Type 1', 'Total', 'HP']).sort_values(by = 'Total', ascending = True)

                          Name Type 1  Total   HP
236                     Slugma   Fire    250   40
42                      Vulpix   Fire    299   38
352                      Numel   Fire    305   60
721                   Fennekin   Fire    307   40
557                      Tepig   Fire    308   65
4                   Charmander   Fire    309   39
435                   Chimchar   Fire    309   44
169                  Cyndaquil   Fire    309   39
276                    Torchic   Fire    310   45
614                   Darumaka   Fire    315   70
572                    Pansear   Fire    316   50
63                   Growlithe   Fire    350   55
259                      Magby   Fire    365   45
735                     Litleo   Fire    369   62
730                Fletchinder   Fire    382   62
5                   Charmeleon   Fire    405   58
436                   Monferno   Fire    405   64
170                    Quilava   Fire    405   58
277                  Combusken   Fire    405   60
722                    Braixen   Fire    409   59
83                      Ponyta   Fire    410   50
237                   Magcargo   Fire    410   50
558                    Pignite   Fire    418   90
353                   Camerupt   Fire    460   70
355                    Torkoal   Fire    470   70
615    DarmanitanStandard Mode   Fire    480  105
692                    Heatmor   Fire    484   85
135                     Magmar   Fire    495   65
573                   Simisear   Fire    498   75
731                 Talonflame   Fire    499   78
84                    Rapidash   Fire    500   65
43                   Ninetales   Fire    505   73
736                     Pyroar   Fire    507   86
147                    Flareon   Fire    525   65
559                     Emboar   Fire    528  110
278                   Blaziken   Fire    530   80
723                    Delphox   Fire    534   75
437                  Infernape   Fire    534   76
6                    Charizard   Fire    534   78
171                 Typhlosion   Fire    534   78
616         DarmanitanZen Mode   Fire    540  105
518                  Magmortar   Fire    540   75
64                    Arcanine   Fire    555   90
354      CameruptMega Camerupt   Fire    560   70
158                    Moltres   Fire    580   90
263                      Entei   Fire    580  115
799                  Volcanion   Fire    600   80
542                    Heatran   Fire    600   91
279      BlazikenMega Blaziken   Fire    630   80
8    CharizardMega Charizard Y   Fire    634   78
7    CharizardMega Charizard X   Fire    634   78
270                      Ho-oh   Fire    680  106

In [27]:
poke.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [35]:
poke.groupby('Name').median('Total')

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,
Abomasnow,460.0,494.0,90.0,92.0,75.0,92.0,85.0,60.0,4.0,0.0
AbomasnowMega Abomasnow,460.0,594.0,90.0,132.0,105.0,132.0,105.0,30.0,4.0,0.0
Abra,63.0,310.0,25.0,20.0,15.0,105.0,55.0,90.0,1.0,0.0
Absol,359.0,465.0,65.0,130.0,60.0,75.0,60.0,75.0,3.0,0.0
AbsolMega Absol,359.0,565.0,65.0,150.0,60.0,115.0,60.0,115.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...
Zoroark,571.0,510.0,60.0,105.0,60.0,120.0,60.0,105.0,5.0,0.0
Zorua,570.0,330.0,40.0,65.0,40.0,80.0,40.0,65.0,5.0,0.0
Zubat,41.0,245.0,40.0,45.0,35.0,30.0,40.0,55.0,1.0,0.0
Zweilous,634.0,420.0,72.0,85.0,70.0,65.0,70.0,58.0,5.0,0.0
Zygarde50% Forme,718.0,600.0,108.0,100.0,121.0,81.0,95.0,95.0,6.0,1.0

In [45]:
poke.sort_values(by = ['Name', 'Total'], ascending = [1, 0])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

In [135]:
poke['summed_rows'] = poke.iloc[0:801, 4:10].sum(axis = 1) # adding rows

In [139]:
poke

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [145]:
poke.to_csv('POKEMON.csv', index = False)

In [21]:
poke.loc[(poke['Type 1'] == 'Grass') & (poke['Type 2'] == 'Poison') & (poke['HP'] > 75)]#.filter(items = ['Name', 'Type 1', 'Type 2', 'Speed', 'Generation']).sort_values(by = 'Generation', ascending = True)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False,490
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False,464

In [9]:
non_mega_part = poke.loc[~poke['Name'].str.contains('Mega')]
non_mega_part

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True,600
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [17]:
non_mega_part.to_csv('non_mega_part.csv', index = False)

In [7]:
filtered = []

for index, row in poke.iterrows():
    if row['HP'] >= 100:
        filtered.append(index)  # Store the row index, not the HP value

print(poke.loc[filtered].filter(items=['Name', 'HP']).sort_values(by='HP', ascending=True))

# print(boolean)
#print(len(boolean))

                        Name   HP
267                Tyranitar  100
427                  Jirachi  100
268  TyranitarMega Tyranitar  100
548                  Manaphy  100
516                Tangrowth  100
..                       ...  ...
655                Alomomola  165
351                  Wailord  170
217                Wobbuffet  190
121                  Chansey  250
261                  Blissey  255

[99 rows x 2 columns]

In [5]:
poke.loc[poke['HP'] >= 100].sort_values(by = 'HP', ascending = True)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
267,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,2,False,600
427,385,Jirachi,Steel,Psychic,100,100,100,100,100,100,3,True,600
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False,700
548,490,Manaphy,Water,NaN,100,100,100,100,100,100,4,False,600
516,465,Tangrowth,Grass,NaN,100,100,125,110,50,50,4,False,535
...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False,470
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False,500
217,202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False,405
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False,450
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False,540

In [77]:
poke.loc[(poke['Type 1'].str.contains('Fire|Grass')) & (poke['Type 2'].str.contains('Water'))]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [83]:
poke.loc[poke['Name'].str.contains('Pi')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,251
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,349
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,479
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False,320
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False,500
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False,205
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False,290
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False,314
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False,264
716,648,MeloettaPirouette Forme,Normal,Fighting,100,128,90,77,77,128,5,False,600

In [85]:
poke.loc[poke['Type 1'] == 'Fire', 'Type 1'] = 'flammer' # conditional changing
poke

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,flammer,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,flammer,Water,80,110,120,130,90,70,6,True,600

In [103]:
poke['Type 1'] = poke['Type 1'].replace('flammer', 'Flamer')# conditional changing

In [105]:
poke

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Flamer,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Flamer,Water,80,110,120,130,90,70,6,True,600

In [107]:
poke.loc[poke['summed_rows'] >= 500, ['Generation', 'Legendary']] = ['test 1', 'test 2']
poke

C:\Users\DELL\AppData\Local\Temp\ipykernel_596\2856931562.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'test 1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  poke.loc[poke['summed_rows'] >= 500, ['Generation', 'Legendary']] = ['test 1', 'test 2']
C:\Users\DELL\AppData\Local\Temp\ipykernel_596\2856931562.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'test 2' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  poke.loc[poke['summed_rows'] >= 500, ['Generation', 'Legendary']] = ['test 1', 'test 2']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,test 1,test 2,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,test 1,test 2,625
4,4,Charmander,Flamer,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,test 1,test 2,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,test 1,test 2,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,test 1,test 2,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,test 1,test 2,680
799,721,Volcanion,Flamer,Water,80,110,120,130,90,70,test 1,test 2,600

In [21]:
poke

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [7]:
poke['Type 2'] = poke['Type 2'].replace('Fairy', 'fairy')

In [9]:
poke

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,summed_rows
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [17]:
groups = poke.groupby(['Type 1', 'Type 2']).count()
groups

                    #  Name  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1   Type 2
Bug      Electric   2     2   2       2        2        2        2      2
         Fighting   2     2   2       2        2        2        2      2
         Fire       2     2   2       2        2        2        2      2
         Flying    14    14  14      14       14       14       14     14
         Ghost      1     1   1       1        1        1        1      1
         Grass      6     6   6       6        6        6        6      6
         Ground     2     2   2       2        2        2        2      2
         Poison    12    12  12      12       12       12       12     12
         Rock       3     3   3       3        3        3        3      3
         Steel      7     7   7       7        7        7        7      7
         Water      1     1   1       1        1        1        1      1
Dark     Dragon     3     3   3       3        3        3        3      3
         Fighting   2     2   2       2        2        2        2      2
         Fire       3     3   3       3        3        3        3      3
         Flying     5     5   5       5        5        5        5      5
         Ghost      2     2   2       2        2        2        2      2
         Ice        2     2   2       2        2        2        2      2
         Psychic    2     2   2       2        2        2        2      2
         Steel      2     2   2       2        2        2        2      2
Dragon   Electric   1     1   1       1        1        1        1      1
         Fire       1     1   1       1        1        1        1      1
         Flying     6     6   6       6        6        6        6      6
         Ground     5     5   5       5        5        5        5      5
         Ice        3     3   3       3        3        3        3      3
         Psychic    4     4   4       4        4        4        4      4
         fairy      1     1   1       1        1        1        1      1
Electric Dragon     1     1   1       1        1        1        1      1
         Fire       1     1   1       1        1        1        1      1
         Flying     5     5   5       5        5        5        5      5
         Ghost      1     1   1       1        1        1        1      1
         Grass      1     1   1       1        1        1        1      1
         Ice        1     1   1       1        1        1        1      1
         Normal     2     2   2       2        2        2        2      2
         Steel      3     3   3       3        3        3        3      3
         Water      1     1   1       1        1        1        1      1
         fairy      1     1   1       1        1        1        1      1
Fairy    Flying     2     2   2       2        2        2        2      2
Fighting Dark       1     1   1       1        1        1        1      1
         Flying     1     1   1       1        1        1        1      1
         Psychic    3     3   3       3        3        3        3      3
         Steel      2     2   2       2        2        2        2      2
Fire     Dragon     1     1   1       1        1        1        1      1
         Fighting   7     7   7       7        7        7        7      7
         Flying     6     6   6       6        6        6        6      6
         Ground     3     3   3       3        3        3        3      3
         Normal     2     2   2       2        2        2        2      2
         Psychic    2     2   2       2        2        2        2      2
         Rock       1     1   1       1        1        1        1      1
         Steel      1     1   1       1        1        1        1      1
         Water      1     1   1       1        1        1        1      1
Flying   Dragon     2     2   2       2        2        2        2      2
Ghost    Dark       1     1   1       1        1        1        1      1
         Dragon     2     2   2       2        2        2        2      2
         Fire       3     3   3       3        3        3        3      3
         Flying     2     2   2       2        2        2        2      2
         Grass     10    10  10      10       10       10       10     10
         Poison     4     4   4       4        4        4        4      4
Grass    Dark       3     3   3       3        3        3        3      3
         Dragon     1     1   1       1        1        1        1      1
         Fighting   3     3   3       3        3        3        3      3
         Flying     5     5   5       5        5        5        5      5
         Ground     1     1   1       1        1        1        1      1
         Ice        3     3   3       3        3        3        3      3
         Poison    15    15  15      15       15       15       15     15
         Psychic    2     2   2       2        2        2        2      2
         Steel      2     2   2       2        2        2        2      2
         fairy      2     2   2       2        2        2        2      2
Ground   Dark       3     3   3       3        3        3        3      3
         Dragon     2     2   2       2        2        2        2      2
         Electric   1     1   1       1        1        1        1      1
         Fire       1     1   1       1        1        1        1      1
         Flying     4     4   4       4        4        4        4      4
         Ghost      2     2   2       2        2        2        2      2
         Psychic    2     2   2       2        2        2        2      2
         Rock       3     3   3       3        3        3        3      3
         Steel      1     1   1       1        1        1        1      1
Ice      Flying     2     2   2       2        2        2        2      2
         Ghost      1     1   1       1        1        1        1      1
         Ground     3     3   3       3        3        3        3      3
         Psychic    2     2   2       2        2        2        2      2
         Water      3     3   3       3        3        3        3      3
Normal   Fighting   2     2   2       2        2        2        2      2
         Flying    24    24  24      24       24       24       24     24
         Grass      2     2   2       2        2        2        2      2
         Ground     1     1   1       1        1        1        1      1
         Psychic    2     2   2       2        2        2        2      2
         Water      1     1   1       1        1        1        1      1
         fairy      5     5   5       5        5        5        5      5
Poison   Bug        1     1   1       1        1        1        1      1
         Dark       3     3   3       3        3        3        3      3
         Dragon     1     1   1       1        1        1        1      1
         Fighting   2     2   2       2        2        2        2      2
         Flying     3     3   3       3        3        3        3      3
         Ground     2     2   2       2        2        2        2      2
         Water      1     1   1       1        1        1        1      1
Psychic  Dark       1     1   1       1        1        1        1      1
         Fighting   3     3   3       3        3        3        3      3
         Fire       1     1   1       1        1        1        1      1
         Flying     6     6   6       6        6        6        6      6
         Ghost      1     1   1       1        1        1        1      1
         Grass      1     1   1       1        1        1        1      1
         fairy      6     6   6       6        6        6        6      6
Rock     Bug        2     2   2       2        2        2        2      2
         Dark       2     2   2       2        2        2        2      2
         Dragon     2     2   2       2        2        2        2      2
         Fighting   1     1   1       1        1        1        1      1
         Flying     4     4   4       4        4        4        4      4
         Grass      2     2   2       2        2        2        2      2
         Ground     6     6   6       6        6        6        6      6
         Ice        2     2   2       2        2        2        2      2
         Psychic    2     2   2       2        2        2        2      2
         Steel      3     3   3       3        3        3        3      3
         Water      6     6   6       6        6        6        6      6
         fairy      3     3   3       3        3        3        3      3
Steel    Dragon     1     1   1       1        1        1        1      1
         Fighting   1     1   1       1        1        1        1      1
         Flying     1     1   1       1        1        1        1      1
         Ghost      4     4   4       4        4        4        4      4
         Ground     2     2   2       2        2        2        2      2
         Psychic    7     7   7       7        7        7        7      7
         Rock       3     3   3       3        3        3        3      3
         fairy      3     3   3       3        3        3        3      3
Water    Dark       6     6   6       6        6        6        6      6
         Dragon     2     2   2       2        2        2        2      2
         Electric   2     2   2       2        2        2        2      2
         Fighting   3     3   3       3        3        3        3      3
         Flying     7     7   7       7        7        7        7      7
         Ghost      2     2   2       2        2        2        2      2
         Grass      3     3   3       3        3        3        3      3
         Ground    10    10  10      10       10       10       10     10
         Ice        3     3   3       3        3        3        3      3
         Poison     3     3   3       3        3        3        3      3
         Psychic    5     5   5       5        5        5        5      5
         Rock       4     4   4       4        4        4        4      4
         Steel      1     1   1       1        1        1        1      1
         fairy      2     2   2       2        2        2        2      2

                   Generation  Legendary  summed_rows
Type 1   Type 2
Bug      Electric           2          2            2
         Fighting           2          2            2
         Fire               2          2            2
         Flying            14         14           14
         Ghost              1          1            1
         Grass              6          6            6
         Ground             2          2            2
         Poison            12         12           12
         Rock               3          3            3
         Steel              7          7            7
         Water              1          1            1
Dark     Dragon             3          3            3
         Fighting           2          2            2
         Fire               3          3            3
         Flying             5          5            5
         Ghost              2          2            2
         Ice                2          2            2
         Psychic            2          2            2
         Steel              2          2            2
Dragon   Electric           1          1            1
         Fire               1          1            1
         Flying             6          6            6
         Ground             5          5            5
         Ice                3          3            3
         Psychic            4          4            4
         fairy              1          1            1
Electric Dragon             1          1            1
         Fire               1          1            1
         Flying             5          5            5
         Ghost              1          1            1
         Grass              1          1            1
         Ice                1          1            1
         Normal             2          2            2
         Steel              3          3            3
         Water              1          1            1
         fairy              1          1            1
Fairy    Flying             2          2            2
Fighting Dark               1          1            1
         Flying             1          1            1
         Psychic            3          3            3
         Steel              2          2            2
Fire     Dragon             1          1            1
         Fighting           7          7            7
         Flying             6          6            6
         Ground             3          3            3
         Normal             2          2            2
         Psychic            2          2            2
         Rock               1          1            1
         Steel              1          1            1
         Water              1          1            1
Flying   Dragon             2          2            2
Ghost    Dark               1          1            1
         Dragon             2          2            2
         Fire               3          3            3
         Flying             2          2            2
         Grass             10         10           10
         Poison             4          4            4
Grass    Dark               3          3            3
         Dragon             1          1            1
         Fighting           3          3            3
         Flying             5          5            5
         Ground             1          1            1
         Ice                3          3            3
         Poison            15         15           15
         Psychic            2          2            2
         Steel              2          2            2
         fairy              2          2            2
Ground   Dark               3          3            3
         Dragon             2          2            2
         Electric           1          1            1
         Fire               1          1            1
         Flying             4          4            4
         Ghost              2          2            2
         Psychic            2          2            2
         Rock               3          3            3
         Steel              1          1            1
Ice      Flying             2          2            2
         Ghost              1          1            1
         Ground             3          3            3
         Psychic            2          2            2
         Water              3          3            3
Normal   Fighting           2          2            2
         Flying            24         24           24
         Grass              2          2            2
         Ground             1          1            1
         Psychic            2          2            2
         Water              1          1            1
         fairy              5          5            5
Poison   Bug                1          1            1
         Dark               3          3            3
         Dragon             1          1            1
         Fighting           2          2            2
         Flying             3          3            3
         Ground             2          2            2
         Water              1          1            1
Psychic  Dark               1          1            1
         Fighting           3          3            3
         Fire               1          1            1
         Flying             6          6            6
         Ghost              1          1            1
         Grass              1          1            1
         fairy              6          6            6
Rock     Bug                2          2            2
         Dark               2          2            2
         Dragon             2          2            2
         Fighting           1          1            1
         Flying             4          4            4
         Grass              2          2            2
         Ground             6          6            6
         Ice                2          2            2
         Psychic            2          2            2
         Steel              3          3            3
         Water              6          6            6
         fairy              3          3            3
Steel    Dragon             1          1            1
         Fighting           1          1            1
         Flying             1          1            1
         Ghost              4          4            4
         Ground             2          2            2
         Psychic            7          7            7
         Rock               3          3            3
         fairy              3          3            3
Water    Dark               6          6            6
         Dragon             2          2            2
         Electric           2          2            2
         Fighting           3          3            3
         Flying             7          7            7
         Ghost              2          2            2
         Grass              3          3            3
         Ground            10         10           10
         Ice                3          3            3
         Poison             3          3            3
         Psychic            5          5            5
         Rock               4          4            4
         Steel              1          1            1
         fairy              2          2            2

In [13]:
pd.set_option('display.max.rows', 137)

In [19]:
groups.to_csv('groups.csv')

In [23]:
filtered = []
for row in poke.HP:
    if row >= 100:
        filtered.append(row)  # This adds the HP value, not the row index
print(poke.loc[filtered])

       #        Name    Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
115  107  Hitmonchan  Fighting     NaN   50     105       79       35
140  130    Gyarados     Water  Flying   95     125       79       60
105   97       Hypno   Psychic     NaN   85      73       70       73
105   97       Hypno   Psychic     NaN   85      73       70       73
250  231      Phanpy    Ground     NaN   90      60       60       40
..   ...         ...       ...     ...  ...     ...      ...      ...
101   94      Gengar     Ghost  Poison   60      65       60      130
123  115  Kangaskhan    Normal     NaN  105      95       80       40
126  117      Seadra     Water     NaN   55      65       95       95
126  117      Seadra     Water     NaN   55      65       95       95
108  100     Voltorb  Electric     NaN   40      30       50       55

     Sp. Def  Speed  Generation  Legendary  summed_rows
115      110     76           1      False          455
140      100     81           1      False          540
105      115     67           1      False          483
105      115     67           1      False          483
250       40     40           2      False          330
..       ...    ...         ...        ...          ...
101       75    110           1      False          500
123       80     90           1      False          490
126       45     85           1      False          440
126       45     85           1      False          440
108       55    100           1      False          330

[99 rows x 13 columns]